-- 코드를 입력하세요
-- SALES_DATE = 2022-01을 기준으로 b.AUTHOR_ID, a.CATEGORY 별 TOTAL_SALES = c.SALES * a.PRICE를 구해서 
-- b.AUTHOR_I, ㅠaAUTHOR_NAME, .CATEGORY, SALES리스트
-- AUTHOR_ID asc, CATEGORY desc
SELECT
  b.AUTHOR_ID,
  b.AUTHOR_NAME,
  a.CATEGORY,
  SUM(c.SALES * a.PRICE) AS TOTAL_SALES
FROM BOOK a
JOIN AUTHOR b     ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES c ON c.BOOK_ID   = a.BOOK_ID
WHERE c.SALES_DATE >= '2022-01-01'
  AND c.SALES_DATE <  '2022-02-01'
GROUP BY
  b.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY
ORDER BY
  b.AUTHOR_ID ASC, a.CATEGORY DESC;