-- 코드를 입력하세요
-- 2022년 1월의 도서판매 데이터
-- TOTAL_SALES = BOOK_SALES.SALES * BOOK.PRICE
-- AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK_CATEGOrY, BOOK_SALES.SALES
-- 저자 ID 를 오름차순, 같으면 CATEGORY를 내림차순
SELECT 
  a.AUTHOR_ID, 
  a.AUTHOR_NAME, 
  b.CATEGORY, 
  SUM(s.SALES * b.PRICE) AS TOTAL_SALES
FROM 
  BOOK b
JOIN 
  AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN 
  BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE 
  s.SALES_DATE LIKE '2022-01%'
GROUP BY 
  a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY 
  a.AUTHOR_ID ASC, b.CATEGORY DESC;
