SELECT CART_ID
FROM (
    SELECT CART_ID,
           GROUP_CONCAT(DISTINCT NAME) AS names
    FROM CART_PRODUCTS
    GROUP BY CART_ID
) t
WHERE names LIKE '%Milk%'
  AND names LIKE '%Yogurt%'
ORDER BY CART_ID;