-- 코드를 입력하세요
-- (SALES_DATE, USER_ID, PRODUCT_ID) 하나의 판매 데이터만
-- (SALES_DATE, PRODUCT_ID) 하나의 판매데이터만
-- SALES_DATE = 2022 03
-- SALES_DATE, PRODUCT_ID, SALES_AMOUNT
-- order by SALES_DATE asc, PRODUCT_ID asc, USER_ID asc
SELECT 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
    PRODUCT_ID, 
    USER_ID, 
    SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
    FROM ONLINE_SALE
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT 
    FROM OFFLINE_SALE
) AS INTEGRATED_SALE
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;