-- 코드를 입력하세요
-- UNIQUE (SALES_DATE, USER_ID, PRODUCT_ID)
-- UNIQUE(SALES_DATE, PRODUCT_ID)
-- SALES_DATE = "2022-03" 
-- SALES_DATE, PRODUCT_ID, USER_ID, count(PRODUCT_ID)
SELECT 
    DATE_FORMAT(T.SALES_DATE, "%Y-%m-%d") as SALES_DATE,
    T.PRODUCT_ID,
    T.USER_ID,
    T.SALES_AMOUNT
FROM 
(
    SELECT *
    FROM ONLINE_SALE
    
    UNION ALL
    
    SELECT 
        OFFLINE_SALE_ID AS ONLINE_SALE_ID,
        NULL AS USER_ID,
        PRODUCT_ID,
        SALES_AMOUNT,
        SALES_DATE
    FROM OFFLINE_SALE        
) AS T

WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
