-- 코드를 입력하세요
-- JOINED = 2021
-- ONLINE_SALE의 USER_ID가 not null
-- YEAR, MONTH 별로 출력
-- round 소수점 두번째 자리
-- YEAR asc, MONTH asc
-- group by YEAR(SALES_DATE)
WITH joined_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT
    YEAR(b.SALES_DATE) AS YEAR,
    MONTH(b.SALES_DATE) AS MONTH,
    COUNT(DISTINCT b.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT b.USER_ID) * 1.0 / (SELECT COUNT(*) FROM joined_2021),
        1
    ) AS PUCHASED_RATIO
FROM ONLINE_SALE b
JOIN joined_2021 j
  ON b.USER_ID = j.USER_ID
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE)
ORDER BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE);
