-- PRODUCE_DATE = "2022-05"
-- a.PRODUCT_ID, a.PRODUCT_NAME, a.PRICE * b.AMOUNT as TOTAL_SALES
-- oroder by TOTAK_SALES desc, PRODUCT_ID asc
-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, sum(a.PRICE * b.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT as a
inner join FOOD_ORDER as b
on a.PRODUCT_ID = b.PRODUCT_ID
where b.PRODUCE_DATE like "2022-05%"
group by a.PRODUCT_ID, a.PRODUCT_NAME
order by TOTAL_SALES desc, b.PRODUCT_ID asc