-- 코드를 입력하세요
-- APNT_YMD = 2022.04.13이고, MCDP_CD = CS, 그리고 APTN_CNCL_YN = 'N'SQL문 작성
-- APNT_NO(3), PT_NAME(1), PT_NO(1, 3), MCDP_CD(3), DR_NAME(2), APNT_YMD(3)
-- ASC -> APNY_YMD를 기준으로
SELECT
  a.APNT_NO,
  b.PT_NAME,
  b.PT_NO,
  a.MCDP_CD,
  c.DR_NAME,
  a.APNT_YMD
FROM APPOINTMENT AS a
JOIN PATIENT AS b
  ON a.PT_NO = b.PT_NO
JOIN DOCTOR AS c
  ON a.MDDR_ID = c.DR_ID
WHERE DATE(a.APNT_YMD) = '2022-04-13'
  AND a.MCDP_CD = 'CS'
  AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD ASC;