SELECT
  e.EMP_NO,
  e.EMP_NAME,
  CASE
    WHEN AVG(g.SCORE) >= 96 THEN 'S'
    WHEN AVG(g.SCORE) >= 90 THEN 'A'
    WHEN AVG(g.SCORE) >= 80 THEN 'B'
    ELSE 'C'
  END AS GRADE,
  CASE
    WHEN AVG(g.SCORE) >= 96 THEN e.SAL * 0.2
    WHEN AVG(g.SCORE) >= 90 THEN e.SAL * 0.15
    WHEN AVG(g.SCORE) >= 80 THEN e.SAL * 0.1
    ELSE 0
  END AS BONUS
FROM HR_EMPLOYEES AS e
JOIN HR_GRADE     AS g
  ON e.EMP_NO = g.EMP_NO
-- (필요하다면 아래처럼 HR_DEPARTMENT도 JOIN)
-- JOIN HR_DEPARTMENT AS d
--   ON e.DEPT_ID = d.DEPT_ID
WHERE g.YEAR = 2022
GROUP BY
  e.EMP_NO,
  e.EMP_NAME,
  e.SAL
ORDER BY
  e.EMP_NO ASC;