-- 2022-08 and 2022-10 -> 총 5회 이상인 것.
-- group by MONTH() -> RECORDS = count(distinct HISTORY_ID)
-- orer by MONTH() asc, CAR_ID desc

WITH cars AS (
  SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
  GROUP BY CAR_ID
  HAVING COUNT(*) >= 5
)
SELECT
  MONTH(b.START_DATE) AS month_no,
  b.CAR_ID,
  COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY b
JOIN cars c ON c.CAR_ID = b.CAR_ID
WHERE b.START_DATE >= '2022-08-01' AND b.START_DATE < '2022-11-01'
GROUP BY MONTH(b.START_DATE), b.CAR_ID
ORDER BY month_no ASC, b.CAR_ID DESC;