-- 코드를 작성해주세요
-- 10cm이하면 NULL. 
-- 종류별로 가장 큰 물고기의 ID, FISH_NAME, LENGTH
SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO a
JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE a.LENGTH > 10
  AND a.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = a.FISH_TYPE AND LENGTH > 10
  )
ORDER BY a.ID;