SELECT CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
WHERE b.SALES IS NOT NULL
  AND MONTH(b.SALES_DATE) = 1
  AND YEAR(b.SALES_DATE) = 2022
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

