-- 코드를 입력하세요
-- 식품분류 (CATEGORY)별로 가격이 제일 비싼 식품 찾기.
-- PRICE 기준으로 내림차순
-- 과자, 국, 김치, 식용유인 경우에만
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
  SELECT CATEGORY, MAX(PRICE)
  FROM FOOD_PRODUCT
  WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
  GROUP BY CATEGORY
)
ORDER BY PRICE DESC;